Sprint 04
kazakovdmitriy/MovieQuiz-ios pull request #2
Opened 2024-01-26 19:55 UTC by kazakovdmitriy

Выполнена логика перехода состояний и вывод результатов

2024-01-28 10:25 UTC, protos17 requested changes

2024-01-28 10:25 UTC, protos17 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +
Настройки закруглений картинки необходимо перенести сюда, чтобы при запуске уже были скругления:

        imageView.layer.masksToBounds = true
        imageView.layer.borderWidth = 8
        imageView.layer.cornerRadius = 20

2024-01-28 10:25 UTC, protos17 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        if currentQuestionIndex == questions.count - 1 {
Здесь необходимо убирать рамку перед показом следующего вопроса:

             imageView.layer.borderColor = UIColor.clear.cgColor

2024-01-28 10:25 UTC, protos17 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        let userAnswer = questions[currentQuestionIndex].correctAnswer==true ? true : false
true и false можно опускать:

     let userAnswer = questions[currentQuestionIndex].correctAnswer == true

2024-01-28 10:25 UTC, protos17 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        let userAnswer = questions[currentQuestionIndex].correctAnswer==false ? true : false
Здесь тоже можно избавиться от true и false

2024-01-28 14:46 UTC, kazakovdmitriy commented
Исправил критические замечания, сделал картинке скругление углов и исправил стиль кнопок. 
Так же по рекомендации изменил статус бар на светлый, вынес модели в отдельные файлы и сделал отключение кнопок, пока формируется следующий вопрос

2024-01-29 10:16 UTC, protos17 approved these changes

2024-01-29 10:16 UTC, protos17 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        noButton.isEnabled = false
Блокировку/разблокировку кнопок рекомендую вынести в отдельный метод, в аргументах которого передавать булевую переменную, в зависимости от которой блокировать или разблокировать кнопки

2024-02-08 09:24 UTC, merged